### PR TITLE
Stabilize Danktronics Bot (Rust)

### PR DESCRIPTION
**Pull request by Sei4or**
### Changes

- [X] New Feature(s)
- [X] Bug Fixes
- [ ] Documentation
- [x] Other: Literally a whole rewrite

## Description

The Rust rewrite is seemingly ready for a stable release and replacement of the aging JS version.

### CODE REVIEW

**Comment by sithsiri** [comment]
I AGREE

**Comment by sithsiri** [comment]
Tested, compiles on Windows. I don't know why it would ever need to compile on Windows, but don't worry! It does. So many warnings though.

**Comment by sithsiri** [comment]
TTS is currently not functional in Windows. Trying to find the issue

**Comment by sithsiri** [comment]
FFmpeg is asking for a file but receiving a URL. Behavior may be different on the target system

**Comment by Sei4or** [comment]
This PR is not for support

**Comment by sithsiri** [comment]
I'M DUMB LOL

**Comment by Sei4or** [comment]
Comments? More like suppression

**Pull request merged**
